//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departments()
        {
            this.Departments1 = new HashSet<Departments>();
            this.SeasonInformation = new HashSet<SeasonInformation>();
        }
    
        public int DepartmentCode { get; set; }
        public int DepartmentTypeCode { get; set; }
        public int HospitalCode { get; set; }
        public Nullable<int> BaseDepartmentCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departments> Departments1 { get; set; }
        public virtual Departments Departments2 { get; set; }
        public virtual DepartmentTypes DepartmentTypes { get; set; }
        public virtual Hospitals Hospitals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeasonInformation> SeasonInformation { get; set; }
    }
}
