//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seasons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seasons()
        {
            this.SeasonInformation = new HashSet<SeasonInformation>();
        }
    
        public int SeasonCode { get; set; }
        public string SeasonName { get; set; }
        public Nullable<System.DateTime> HebrewDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public int NumOfDays { get; set; }
        public bool IsDefined { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeasonInformation> SeasonInformation { get; set; }
    }
}
